name: linux-x64

on:
  push:
    paths-ignore:
      - 'README'
      - 'kdllar.txt'
      - 'COPYING.LIB'
      - '.gitignore'
      - '.gitattributes'
      - '.github/FUNDING.yml'

  pull_request:
    paths-ignore:
      - 'README'
      - 'kdllar.txt'
      - 'COPYING.LIB'
      - '.gitignore'
      - '.gitattributes'
      - '.github/FUNDING.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: make

      - name: Setup cross-os2emx env
        uses: komh/setup-cross-os2emx@v1

      - name: Test
        run: |
          make test CC="i686-pc-os2-emx-gcc"
